pub mod dir_guard;

use std::path::PathBuf;

use crate::context::GeneratorContext;
use crate::openapi::normalize::normalize_operations;
use crate::openapi::parse::OpenApiDocument;
use crate::project_config::{AuthOverride, HeaderSetting, ProjectSettings, write_settings};
use crate::{auth_profile, db, openapi};
use anyhow::Result;

/// Glues the shared, target-independent steps of the compile-time lifecycle
/// (architecture.md §1, steps 1-4) into the fully populated
/// `GeneratorContext` every `McpServerTargetGenerator` method then receives:
/// ingest & parse -> directory guard -> auth profiling -> operation
/// normalization -> `mcp_store.db` assembly, run once regardless of
/// `--language`.
///
/// Mirrors `execute()`'s rollback semantics (architecture.md's default
/// `execute` body): once the directory guard has run, any later failure in
/// this same shared pipeline removes a freshly-created `output_dir` before
/// returning the error, so a spec that fails auth profiling (for example)
/// doesn't leave an empty directory behind for the next attempt to trip
/// over. A pre-existing (`--force`) directory is never touched.
#[allow(clippy::too_many_arguments)]
pub async fn run_shared_pipeline(
    input: &str,
    output_dir: PathBuf,
    force: bool,
    interactive_auth_prompt: bool,
    publish_registry: bool,
    version_label: &str,
) -> Result<GeneratorContext> {
    let project_name = output_dir
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("mcpify-client");
    let settings = ProjectSettings {
        default_headers: vec![HeaderSetting {
            name: "User-Agent".to_string(),
            value: format!("{project_name}/0.1.0 (generated by mcpify)"),
        }],
        ..ProjectSettings::default()
    };
    run_shared_pipeline_with_settings(
        input,
        output_dir,
        force,
        interactive_auth_prompt,
        publish_registry,
        version_label,
        &settings,
        &[],
    )
    .await
}

#[allow(clippy::too_many_arguments)]
pub async fn run_shared_pipeline_with_settings(
    input: &str,
    output_dir: PathBuf,
    force: bool,
    interactive_auth_prompt: bool,
    publish_registry: bool,
    version_label: &str,
    settings: &ProjectSettings,
    auth_overrides: &[AuthOverride],
) -> Result<GeneratorContext> {
    if crate::progress::enabled() {
        eprintln!("==> Fetching OpenAPI spec from {input}");
    }
    let doc = openapi::ingest(input).await?;

    if crate::progress::enabled() {
        eprintln!("==> Preparing output directory {}", output_dir.display());
    }
    let output_dir_preexisted = dir_guard::check_output_dir(&output_dir, force).await?;
    write_settings(&output_dir, settings).await?;

    let result = assemble_context(
        input,
        output_dir.clone(),
        force,
        output_dir_preexisted,
        interactive_auth_prompt,
        publish_registry,
        version_label,
        auth_overrides,
        &doc,
    )
    .await;

    if result.is_err() && !output_dir_preexisted {
        let _ = tokio::fs::remove_dir_all(&output_dir).await;
    }

    result
}

#[allow(clippy::too_many_arguments)]
async fn assemble_context(
    input: &str,
    output_dir: PathBuf,
    force: bool,
    output_dir_preexisted: bool,
    interactive_auth_prompt: bool,
    publish_registry: bool,
    version_label: &str,
    auth_overrides: &[AuthOverride],
    doc: &OpenApiDocument,
) -> Result<GeneratorContext> {
    if crate::progress::enabled() {
        eprintln!("==> Profiling auth schemes");
    }
    let auth_schemes =
        auth_profile::profile_auth_with_overrides(doc, interactive_auth_prompt, auth_overrides)
            .await?;

    if crate::progress::enabled() {
        eprintln!("==> Normalizing operations");
    }
    let normalized_operations = normalize_operations(doc);
    if crate::progress::enabled() {
        eprintln!("==> Found {} operations", normalized_operations.len());
    }

    let ctx = GeneratorContext {
        publish_registry,
        openapi_input: input.to_string(),
        output_dir,
        force,
        output_dir_preexisted,
        auth_schemes,
        normalized_operations,
        api_title: doc.title().to_string(),
        version_label: version_label.to_string(),
    };

    if crate::progress::enabled() {
        eprintln!("==> Assembling mcp_store.db");
    }
    db::assemble_store(&ctx).await?;

    Ok(ctx)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn assembles_a_full_context_from_a_fixture_spec() {
        let parent = tempfile::tempdir().unwrap();
        let output_dir = parent.path().join("generated"); // does not exist yet

        let ctx = run_shared_pipeline(
            "tests/fixtures/openapi/minimal-with-auth.yaml",
            output_dir.clone(),
            false,
            false,
            false,
            "default",
        )
        .await
        .unwrap();

        assert_eq!(ctx.auth_schemes.len(), 1);
        assert!(!ctx.output_dir_preexisted);
        assert_eq!(ctx.normalized_operations.len(), 1);
        assert_eq!(ctx.normalized_operations[0].operation_id, "ping");
        assert!(output_dir.join("mcp_store.db").exists());
    }

    #[tokio::test]
    async fn propagates_ingest_failure_without_creating_output_dir() {
        let parent = tempfile::tempdir().unwrap();
        let output_dir = parent.path().join("generated");

        let err = run_shared_pipeline(
            "tests/fixtures/openapi/does-not-exist.yaml",
            output_dir.clone(),
            false,
            false,
            false,
            "default",
        )
        .await
        .unwrap_err();

        assert!(err.to_string().contains("failed to read OpenAPI spec"));
        assert!(!output_dir.exists());
    }

    #[tokio::test]
    async fn rolls_back_a_freshly_created_dir_when_auth_profiling_fails() {
        let parent = tempfile::tempdir().unwrap();
        let output_dir = parent.path().join("generated");

        let err = run_shared_pipeline(
            "tests/fixtures/openapi/minimal-no-auth-scheme.json",
            output_dir.clone(),
            false,
            false,
            false,
            "default",
        )
        .await
        .unwrap_err();

        assert!(err.to_string().contains("no usable auth scheme found"));
        assert!(!output_dir.exists());
    }

    #[tokio::test]
    async fn preserves_a_preexisting_dir_when_auth_profiling_fails() {
        let dir = tempfile::tempdir().unwrap();
        let marker = dir.path().join("keep-me.txt");
        tokio::fs::write(&marker, b"partial content from a previous run")
            .await
            .unwrap();

        run_shared_pipeline(
            "tests/fixtures/openapi/minimal-no-auth-scheme.json",
            dir.path().to_path_buf(),
            true,
            false,
            false,
            "default",
        )
        .await
        .unwrap_err();

        assert!(marker.exists());
    }
}
